# Generated by Django 4.0 on 2022-01-08 06:25

import apps.camp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_alter_user_birthday_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='營隊名稱', max_length=150, unique=True)),
                ('introduction', models.CharField(help_text='活動介紹', max_length=2000)),
                ('cover_photo', models.ImageField(blank=True, help_text='活動圖片', upload_to=apps.camp.models.camp_file_path)),
                ('school', models.CharField(blank=True, help_text='學校名稱', max_length=50)),
                ('department', models.CharField(blank=True, help_text='系所名稱', max_length=75)),
                ('is_public', models.BooleanField(default=False, help_text='是否公開')),
                ('camp_start_date', models.DateField(blank=True, help_text='營隊開始時間')),
                ('camp_end_date', models.DateField(blank=True, help_text='營隊結束時間')),
                ('register_start_date', models.DateTimeField(help_text='報名開始時間')),
                ('register_end_date', models.DateTimeField(help_text='報名結束時間')),
                ('template_data', models.CharField(help_text='其他模板資料 之後再改', max_length=200)),
                ('host', models.ForeignKey(help_text='營隊創辦人', on_delete=django.db.models.deletion.CASCADE, related_name='host_activity', to='user.user')),
            ],
            options={
                'db_table': 'camp',
            },
        ),
    ]
