# Generated by Django 4.0 on 2022-01-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0002_remove_camp_department_remove_camp_introduction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='fee',
            field=models.PositiveIntegerField(default=0, help_text='活動費用'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='quota',
            field=models.PositiveIntegerField(default=100, help_text='活動名額'),
        ),
    ]
