# Generated by Django 4.0 on 2022-01-09 06:19

import apps.camp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0003_alter_camp_fee_alter_camp_quota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='cover_photo',
            field=models.FileField(blank=True, help_text='活動圖片', upload_to=apps.camp.models.camp_file_path),
        ),
    ]
