# Generated by Django 4.0 on 2022-01-11 16:48

import apps.camp.models
import apps.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0005_alter_camp_camp_end_date_alter_camp_camp_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='cover_photo',
            field=models.FileField(blank=True, help_text='活動圖片', storage=apps.storage_backends.PublicMediaStorage(), upload_to=apps.camp.models.camp_file_path),
        ),
    ]
