# Generated by Django 4.0 on 2022-01-12 12:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0007_camp_questions_alter_camp_camp_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='category',
            field=models.PositiveIntegerField(choices=[(1, '文法類'), (2, '財經類'), (3, '理工類'), (4, '醫護類'), (5, '其他')], default=5, help_text='營隊類組'),
        ),
        migrations.AddField(
            model_name='camp',
            name='short_description',
            field=models.CharField(blank=True, default='', help_text='營隊簡短介紹', max_length=200),
        ),
        migrations.AlterField(
            model_name='camp',
            name='questions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(verbose_name='問題 key'), help_text='使用之問題', null=True, size=None),
        ),
    ]
