# Generated by Django 4.0 on 2022-01-14 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0008_camp_category_camp_short_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camp',
            name='questions',
        ),
    ]
