# Generated by Django 4.0 on 2022-01-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0010_camp_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='is_public',
            field=models.BooleanField(db_index=True, default=True, help_text='是否公開'),
        ),
    ]
