# Generated by Django 4.0 on 2021-12-22 07:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='', help_text='名字', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='if_agree',
            field=models.BooleanField(default=False, help_text='是否同意服務條款和資料政策'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='', help_text='姓氏', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='', help_text='用戶名稱', max_length=50),
        ),
    ]
