# Generated by Django 4.0 on 2022-01-11 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0004_rename_first_name_user_name_alter_user_last_name'),
        ('camp', '0006_alter_camp_cover_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', help_text='姓名', max_length=50)),
                ('sex', models.CharField(default='', help_text='生理性別', max_length=50)),
                ('nationality', models.CharField(blank=True, default='', help_text='國籍', max_length=100)),
                ('id_number', models.CharField(blank=True, default='', help_text='身分證字號', max_length=10)),
                ('birth_date', models.DateField(help_text='出生年月日', null=True)),
                ('school_and_grade', models.CharField(blank=True, default='', help_text='學校名稱與年級', max_length=200, verbose_name='School name and grade')),
                ('special_disease', models.CharField(blank=True, default='', help_text='特殊疾病', max_length=500)),
                ('fb_link', models.URLField(help_text='臉書連結', null=True, verbose_name='Facebook Link')),
                ('eating_habit', models.CharField(blank=True, default='', help_text='飲食習慣', max_length=200)),
                ('email', models.EmailField(help_text='E-mail 必填', max_length=254)),
                ('contact_number', models.CharField(blank=True, default='', help_text='聯絡電話', max_length=20)),
                ('guardian_name', models.CharField(blank=True, default='', help_text='監護人 姓名', max_length=100)),
                ('guardian_relationship', models.CharField(blank=True, default='', help_text='與監護人之關係', max_length=50)),
                ('guardian_contact_number', models.CharField(blank=True, default='', help_text='監護人聯絡電話', max_length=20)),
                ('introduction', models.TextField(blank=True, default='', help_text='自我介紹', max_length=3000)),
                ('special_experience', models.TextField(blank=True, default='', help_text='特殊經歷', max_length=3000)),
                ('motivation', models.TextField(blank=True, default='', help_text='報名動機', max_length=3000)),
                ('camp_anticipation', models.TextField(blank=True, default='', help_text='對營隊的期許', max_length=3000)),
                ('other', models.TextField(blank=True, default='', help_text='其他', max_length=3000)),
                ('camp', models.ForeignKey(help_text='所屬營隊', on_delete=django.db.models.deletion.CASCADE, related_name='register_user', to='camp.camp')),
                ('user', models.ForeignKey(help_text='所屬用戶', on_delete=django.db.models.deletion.CASCADE, related_name='register', to='user.user')),
            ],
            options={
                'db_table': 'registration',
            },
        ),
    ]
