# Generated by Django 4.0 on 2022-01-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='is_finish',
            field=models.BooleanField(default=False, help_text='是否完成報名填寫'),
        ),
    ]
