# Generated by Django 4.0 on 2022-01-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_registration_is_finish'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.UniqueConstraint(fields=('camp', 'user'), name='unique-camp-for-user'),
        ),
    ]
