# Generated by Django 4.0 on 2022-01-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_registration_unique-camp-for-user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='school_and_grade',
        ),
        migrations.AddField(
            model_name='registration',
            name='grade',
            field=models.CharField(blank=True, default='', help_text='年級', max_length=20, verbose_name='Grade'),
        ),
        migrations.AddField(
            model_name='registration',
            name='school',
            field=models.CharField(blank=True, default='', help_text='學校名稱', max_length=200, verbose_name='School name'),
        ),
    ]
