# Generated by Django 4.0 on 2022-01-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_remove_registration_school_and_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='is_finish',
            field=models.BooleanField(default=True, help_text='是否完成報名填寫'),
        ),
    ]
