# Generated by Django 4.0 on 2022-01-15 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_alter_registration_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='grade',
        ),
        migrations.AlterField(
            model_name='registration',
            name='school',
            field=models.CharField(blank=True, default='', help_text='學校名稱和年級', max_length=200, verbose_name='School_and_grade'),
        ),
    ]
